version: '3.7'
services:
  neo4j:
    image: neo4j:4.4
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"  # HTTP port for Neo4j web interface
      - "7687:7687"  # Bolt protocol port for Go application to connect
    volumes:
      - neo4j_data:/var/lib/neo4j/data
      - neo4j_logs:/var/lib/neo4j/logs

volumes:
  neo4j_data:
  neo4j_logs:
 
