apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-backend
  template:
    metadata:
      labels:
        app: go-backend
    spec:
      containers:
        - name: go-backend
          image: cedrickah/overtodo-app-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: NEO4J_URI
              value: "neo4j://neo4j:7687" # Connect to Neo4j container via Kubernetes service
            - name: NEO4J_HOST
              value: neo4j-service
            - name: NEO4J_PORT
              value: "7687"
---
apiVersion: v1
kind: Service
metadata:
  name: go-backend
spec:
  selector:
    app: go-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
